version: 2

jobs:
  build:
    docker:
        - image: novopl/python36:ci-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps-rev1-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: tox-rev2-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}

      - run:
          name: Setup dependencies
          command: |
            which pip
            which python
            pip install -r requirements.txt
            pip install -r ops/devrequirements.txt
            peltak --help
            python setup.py develop

      - run:
          name: Lint
          command: peltak lint

      - run:
          name: Test
          command: tox

      - save_cache:
          key: tox-rev2-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}
          paths:
          - .tox

      - run:
          name: Generate Docs
          command: peltak docs

      - store_test_results:
          path: .build
      - store_artifacts:
          path: .build/coverage/
          destination: coverage
      - store_artifacts:
          path: docs/html
          destination: docs

  release:
    docker:
      - image: novopl/python36:ci-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps-rev1-{{ checksum "requirements.txt" }}
      - run: python setup.py develop
      - run: peltak release gen-pypirc
      - run: peltak release upload pypi
      - run: rm ~/.pypirc
      - run: peltak release tag
      - run: "git push origin v$(peltak version --porcelain)"


workflows:
  version: 2
  full_pipe:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
